import { ParsedUrlQuery } from 'querystring';
import type { NextPage, InferGetStaticPropsType, GetStaticProps } from 'next';
import Head from 'next/head';
import { RiChatNewLine } from 'react-icons/ri';
import { Heading } from '@/components/app/Heading';
import { Posts } from '@/components/app/Posts';
import { Post } from '@/types';
import { getPosts } from '@/utils/getPosts';

type Props = {
  posts: Post[];
};

type Params = ParsedUrlQuery;

const View: NextPage<InferGetStaticPropsType<typeof getStaticProps>> = ({
  posts,
}) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading icon={<RiChatNewLine />} text="home">
        最新の記事
      </Heading>
      <Posts posts={posts} />
    </>
  );
};

export default View;

export const getStaticProps: GetStaticProps<Props, Params> = async () => {
  return {
    props: {
      posts: getPosts(),
    },
  };
};
