import { ParsedUrlQuery } from 'querystring';
import type {
  InferGetStaticPropsType,
  GetStaticProps,
  NextPageWithLayout,
} from 'next';
import Head from 'next/head';
import { RiChatNewLine } from 'react-icons/ri';
import { Contents } from '@/components/app/Contents';
import { Header } from '@/components/app/Header';
import { Heading } from '@/components/app/Heading';
import { Posts } from '@/components/app/Posts';
import { Grid } from '@/components/common/Layout';
import { Hero } from '@/components/home/Hero';
import { Post } from '@/types';
import { getPosts } from '@/utils/getPosts';

type Props = {
  posts: Post[];
};

type Params = ParsedUrlQuery;

const View: NextPageWithLayout<
  InferGetStaticPropsType<typeof getStaticProps>
> = ({ posts }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading icon={<RiChatNewLine />} text="home">
        最新の記事
      </Heading>
      <Posts posts={posts} />
    </>
  );
};

View.getLayout = (page) => (
  <div className="global-layout">
    <Grid
      className="global-layout__header"
      css={{
        overflow: 'hidden',
        h: '100vh',
        gridTemplateRows: 'auto 1fr',
      }}
    >
      <Header />
      <Hero />
    </Grid>
    <Contents className="global-layout__contents">{page}</Contents>
  </div>
);

export default View;

export const getStaticProps: GetStaticProps<Props, Params> = async () => {
  return {
    props: {
      posts: getPosts(),
    },
  };
};
