import { ParsedUrlQuery } from 'querystring';
import type {
  NextPage,
  GetStaticProps,
  GetStaticPaths,
  InferGetStaticPropsType,
} from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { BsHash } from 'react-icons/bs';
import { Heading } from '@/components/app/Heading';
import { Post } from '@/types';
import { formatDate } from '@/utils/format';
import { getPostsByTag } from '@/utils/getPosts';
import { getTags } from '@/utils/getTags';

type Props = {
  tag: string;
  posts: Post[];
};

type Params = ParsedUrlQuery & {
  tag: string;
};

const View: NextPage<InferGetStaticPropsType<typeof getStaticProps>> = ({
  tag,
  posts,
}: Props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading icon={<BsHash />} text="tag">{tag}の記事</Heading>
      <ul>
        {posts.map((post) => (
          <li key={post.slug}>
            <Link href={`/${post.year}/${post.month}/${post.slug}`}>
              <a>{post.title}</a>
            </Link>
            <div>{formatDate(post.date)}</div>
          </li>
        ))}
      </ul>
    </>
  );
};

export default View;

export const getStaticProps: GetStaticProps<Props, Params> = async ({
  params,
}) => {
  const { tag } = params as Params;

  return {
    props: {
      tag,
      posts: getPostsByTag(tag),
    },
  };
};

export const getStaticPaths: GetStaticPaths<Params> = async () => {
  const paths = getTags().map((tag) => ({
    params: { tag },
  }));

  return {
    paths,
    fallback: false,
  };
};
